# Generated by Django 3.0 on 2026-02-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='escalate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='permissions/'),
        ),
    ]
