# Generated by Django 3.0 on 2026-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20260203_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('forwarded', 'Forwarded'), ('auto_escalated', 'Auto Escalated'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
