# Generated by Django 3.0 on 2026-02-06 04:49

from django.db import migrations, models
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20260203_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='request_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=permissions.models.permission_upload_path),
        ),
    ]
