# Generated by Django 3.0 on 2026-02-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_auto_20260206_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='request_code',
            field=models.CharField(blank=True, default='TMP-OLD', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
