# Generated by Django 3.0 on 2026-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_auto_20260206_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
