# Generated by Django 3.0 on 2026-02-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20260206_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('forwarded', 'Forwarded'), ('auto_escalated', 'Auto Escalated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('urgent_warning_sent', 'Urgent Warning Sent')], max_length=20),
        ),
    ]
