# Generated by Django 3.0 on 2026-02-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_auto_20260208_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
