# Generated by Django 3.0 on 2026-02-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0010_auto_20260211_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAIInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('needs_info', 'Needs Info'), ('review', 'Review')], default='review', max_length=20)),
                ('flags', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='rule-v1', max_length=20)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='permissions.PermissionRequest')),
            ],
        ),
    ]
