# Generated by Django 6.0.3 on 2026-03-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0011_permissionaiinsight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionaiinsight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="requesthistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
