# Generated by Django 5.1.3 on 2026-03-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0012_alter_permissionaiinsight_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionrequest",
            name="urgent_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requesthistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("forwarded", "Forwarded"),
                    ("auto_escalated", "Auto Escalated"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reassigned", "Reassigned"),
                    ("deleted", "Deleted"),
                    ("urgent_warning_sent", "Urgent Warning Sent"),
                ],
                max_length=20,
            ),
        ),
    ]
