# Generated by Django 3.0 on 2026-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dean_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
