# Generated by Django 3.0 on 2026-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_dean_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('hod', 'HOD'), ('dean', 'Dean'), ('principal', 'Principal')], max_length=20),
        ),
    ]
