# Generated by Django 3.0 on 2026-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20260216_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dean_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
