# Generated by Django 3.0 on 2026-03-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
