# Generated by Django 3.0 on 2026-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('AIML', 'AI & Machine Learning'), ('IT', 'Information Technology'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering'), ('EEE', 'Electrical Engineering')], max_length=20),
        ),
    ]
