# Generated by Django 6.0.3 on 2026-03-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_auto_20260315_1359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetotp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dean_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Academic Affairs", "Academic Affairs"),
                    ("R&D", "R&D"),
                    ("Student Affairs", "Student Affairs"),
                    ("Placements", "Placements"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CSE", "Computer Science"),
                    ("ECE", "Electronics"),
                    ("AIML", "AI & Machine Learning"),
                    ("IT", "Information Technology"),
                    ("CIVIL", "Civil Engineering"),
                    ("MECH", "Mechanical Engineering"),
                    ("EEE", "Electrical Engineering"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
