# Generated by Django 5.1.3 on 2026-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_passwordresetotp_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="college",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aditya University", "Aditya University"),
                    (
                        "Aditya College of Engineering and Technology",
                        "Aditya College of Engineering and Technology",
                    ),
                    ("Aditya College of Engineering", "Aditya College of Engineering"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
