# Generated by Django 3.0 on 2026-03-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20260304_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='ai_summary_created_at',
        ),
        migrations.AddField(
            model_name='meeting',
            name='audience_type',
            field=models.CharField(choices=[('students', 'Students'), ('staff', 'Staff'), ('both', 'Both')], default='students', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='MeetingRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='meetings.Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
