# Generated by Django 3.0 on 2026-03-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20260307_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='left_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='audience_type',
            field=models.CharField(choices=[('students', 'Students'), ('staff', 'Staff'), ('both', 'Both'), ('hod', 'HOD'), ('dean', 'Dean'), ('all', 'All')], default='students', max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingWhiteboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard', to='meetings.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='meetings.Meeting')),
            ],
        ),
    ]
