# Generated by Django 3.0 on 2026-03-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20260312_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration_minutes',
        ),
    ]
