# Generated by Django 3.0 on 2026-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_remove_meeting_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
