# Generated by Django 3.0 on 2026-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meeting_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
